name: aliortho
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_modular: ^5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.0"
  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: true
  ios: true
  adaptive_icon_background: "#FFFFFF" # Pode ser uma cor hexadecimal ou uma imagem
  adaptive_icon_foreground: "assets/playstore.png" # Caminho para a camada de primeiro plano
  min_sdk_android: 21
  image_path:  "assets/playstore.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Lexend
      fonts:
        - asset: assets/fonts/Lexend-Black.ttf
        - asset: assets/fonts/Lexend-Bold.ttf
        - asset: assets/fonts/Lexend-ExtraBold.ttf